# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41527ee108a63d956bf33ad7fd4250c4908b9eeaa9aaa24bed5e3077ab28ddc2eb7f88a8aaa2ffd388d1dd9b061f772eb296262c851c40e257577362b65e4c25

test:
  secret_key_base: 760fb9cf3a0b957d68e6a548a9fac973820e37dbe6aeba7d20eed5cf2e9f3ffaf6dba6c18d97cf05e68f684961ea3a1b155c63d48eb05b4a76a624db53240587

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
